# ClusterConfig object for gpt app:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-app
  region: us-east-1

nodeGroups:
  - name: capstone-app-worker-nodes
    instanceType: t2.medium
    minSize: 1
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      publicKeyName: udacity