apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone-app
        image: anhntp/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: capstone-app
  type: LoadBalancer
