Description: >
  Elastic Container Registry for capstoneApp.

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "capstoneApp"
      ImageScanningConfiguration:
          ScanOnPush: true

Outputs:
  RepositoryUri:
    Value: !GetAtt ECR.RepositoryUri