MyRepository: 
  Type: AWS::ECR::Repository
  Properties: 
    RepositoryName: "capstoneRepo"
    ImageScanningConfiguration: 
      ScanOnPush: true

Outputs:
  RepositoryUri:
    Value: !GetAtt ECR.RepositoryUri