---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy
  labels:
    name: capstone-deploy
    app: capstone-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      name: capstone-pod
      app: capstone-app
  template:
    metadata:
      name: capstone-pod
      labels:
        name: capstone-pod
        app: capstone-app
    spec:
      containers:
      - name: capstone
        image: DOCKER_IMAGE_NAME:VERSION_INFO_VALUE
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80