---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    name: capstone-service
    app: capstone-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: capstone-pod
    app: capstone-app
