# ClusterConfig object for gpt app:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-app
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0467bfc4a1bc7d32d }
      us-east-1b: { id: subnet-02dec75e8faa31f2c }
      us-east-1c: { id: subnet-035b02ce68081271a }
nodeGroups:
  - name: capstone-app-worker-nodes
    instanceType: t2.medium
    minSize: 1
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      publicKeyName: udacity